CREATE EXTENSION IF NOT EXISTS pgcrypto;

DROP TABLE IF EXISTS public.projects;

CREATE TABLE public.projects (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    title text NOT NULL,
    slug text NOT NULL,
    subtitle text,
    year text,
    technologies text,
    categories text,
    filters text[],
    image text,
    description text[],
    conclusion text[],
    video text,
    "livePreview" text,
    "nextProjectSlug" text,
    "projectImg" text[]
);

COPY public.projects (id, created_at, title, slug, subtitle, year, technologies, categories, filters, image, description, conclusion, video, "livePreview", "nextProjectSlug", "projectImg") FROM stdin;
a5e82f1a-2416-4e20-9656-4737af112d05	2025-04-06 07:01:29.46663+00	BizFlow	bizflow	Business Workflow Automation Tool	2024	Power Automate, SharePoint	Business Process Automation	{sorting-business-process-automation}	assets/images/bizflow.jpg	{"Optimizes workflows like approvals, data entry, and reporting.","Supports drag-and-drop automation builder and integration with Microsoft services."}	{"Reduced manual tasks by 60% in client use case.","Planned AI rule suggestions and Teams bot integration."}	https://www.youtube.com/embed/dQw4w9WgXcQ	https://bizflow.example.com	scriptease	\N
178e097f-5ae4-4604-b173-d705c791f14b	2025-04-06 07:01:29.46663+00	ScriptEase	scriptease	Task Automation with Scripting & AI	2023	Python, JavaScript, OpenAI	Scripting & AI Automations	{sorting-scripting-and-automations}	assets/images/scriptease.jpg	{"Helps automate repetitive computer tasks like file renaming, report generation, and more.","Includes built-in scripting editor and natural language AI prompts."}	{"Saved developers 5–10 hours/week on repetitive tasks.","AI prompt-to-script feature coming soon."}	https://www.youtube.com/embed/dQw4w9WgXcQ	https://scriptease.example.com	powersuite	\N
3c04d597-a5f0-4f48-a170-88ae41e0d3a1	2025-04-06 07:01:29.46663+00	PowerSuite	powersuite	Enterprise-Grade RPA and Power Platform Toolkit	2023	Power Automate, PAD, Power Apps	RPA & Power Platform	{sorting-rpa-and-power-platform}	assets/images/powersuite.jpg	{"Combines RPA with Microsoft's Power Platform for end-to-end automation.","Handles invoice processing, user provisioning, and system health checks."}	{"Automated 80% of repetitive admin tasks in pilot.","Planned AI sentiment analysis for customer requests."}	https://www.youtube.com/embed/dQw4w9WgXcQ	https://powersuite.example.com	devcraft	\N
598117ab-7adb-451a-ae34-39d500764fb0	2025-04-06 07:01:29.46663+00	AutoBiz	autobiz	Workflow & Operations Automation	2022	Zapier, Make.com, Google Workspace	Business Process Automation	{sorting-business-process-automation}	assets/images/autobiz.jpg	{"Automates client onboarding, data transfers, CRM updates, and reporting.","Integrates with 50+ tools including CRMs, spreadsheets, and emails."}	{"Enabled 24/7 workflow reliability without manual input.","Next step: automation health monitoring dashboard."}	https://www.youtube.com/embed/dQw4w9WgXcQ	https://autobiz.example.com	codebot	\N
4081aac7-f172-4fc1-816c-c5710d3f5ee7	2025-04-06 07:01:29.46663+00	CodeBot	codebot	AI-Powered Development Assistant	2023	OpenAI, GitHub Copilot API, VSCode Extension	Scripting & AI Automations	{sorting-scripting-and-automations}	assets/images/codebot.jpg	{"Helps developers write and debug code faster using AI-powered suggestions.","Integrates with GitHub, VSCode, and terminal."}	{"Improved code quality in 90% of developer feedback surveys.","Roadmap: collaborative pair programming AI."}	https://www.youtube.com/embed/dQw4w9WgXcQ	https://codebot.example.com	flowpro	\N
2b3d8953-186c-42b7-82c2-9e8057b2aaf5	2025-04-06 07:01:29.46663+00	FlowPro	flowpro	Advanced Workflow Automation with RPA	2023	Power Automate Desktop, SharePoint	RPA & Power Platform	{sorting-rpa-and-power-platform}	assets/images/flowpro.jpg	{"Designed for enterprise-grade automation of finance, HR, and operations processes.","Features logging, retry logic, and error alerts."}	{"Cut reconciliation time from 3 days to 2 hours in a client test case.","Planned: analytics dashboards and approval chains."}	https://www.youtube.com/embed/dQw4w9WgXcQ	https://flowpro.example.com	noirak	\N
bfc3b985-e633-4e2b-a65d-d3c1b5f41ecd	2025-04-06 07:01:29.46663+00	Noirak Technologies	noirak	Modern Project Management Web App	2024	Next.js, Typescript, Tailwind, ChakraUI, Redux, Formik, Framer-Motion, Node.js, PostgresQL	Web Development	{sorting-web-development}	https://res.cloudinary.com/tobycodes/image/upload/v1743938639/Portfolio%20V2/noirak/Noirak_w1ooox.png	{"Noirak.com is the digital home of a fast-growing tech startup focused on innovative software solutions for African businesses. As the Lead Engineer, I was responsible for designing and building the website from the ground up, ensuring it reflected the brand’s forward-thinking identity while remaining performant and user-friendly.","The site is built with Next.js for fast static and dynamic rendering, Chakra UI for a responsive and accessible design system, and integrated with PostgresQl on the backend. Core features include a modern landing page, detailed service sections, customer dashboard and admin portal for managing loans.","This project demanded a deep understanding of both frontend engineering and UX strategy, with special focus on page performance, SEO optimization, and mobile-first design principles."}	{"Noirak.com has evolved into more than just a marketing site—it's a full-fledged, scalable platform tailored to both users and administrators. I led the development of the landing page to clearly communicate the brand's value, and I also built the customer dashboard and admin portal used to manage loan applications, approvals, and customer data. Powered by a clean architecture using Next.js and Supabase, the platform is fast, secure, and built for scale—delivering a seamless experience across all user roles."}	https://www.youtube.com/embed/dQw4w9WgXcQ	https://www.noirak.com	bizflow	{https://res.cloudinary.com/tobycodes/image/upload/v1743928847/Portfolio%20V2/noirak/Screenshot_2025-04-06_092410_s2p7xe.png,https://res.cloudinary.com/tobycodes/image/upload/v1743928847/Portfolio%20V2/noirak/Screenshot_2025-04-06_092738_ikyhqi.png,https://res.cloudinary.com/tobycodes/image/upload/v1743936255/Portfolio%20V2/noirak/Screenshot_2025-04-06_093601_jyulo7.png,https://res.cloudinary.com/tobycodes/image/upload/v1743928845/Portfolio%20V2/noirak/Screenshot_2025-04-06_092439_aagbtt.png}
4a47781a-75f0-441b-a810-9530feea5b5a	2025-04-06 07:01:29.46663+00	LagosNet	lagosnet	EPPPS Automated E-Planning Permit Landing Page	2022	React.js, Tailwind, ChakraUI, Redux	Web Development	{sorting-web-development}	https://res.cloudinary.com/tobycodes/image/upload/v1743938640/Portfolio%20V2/LASGNET_yi4y56.png	{"Lagos EPPPS (Electronic Physical Planning Permit System) was built as the digital gateway for the Lagos State Planning Permit Office. I led the development of a modern, responsive website that connects the public to essential resources—including the E-Permit Portal and planning policy documents—through a clean and intuitive interface.","Beyond the website, I redesigned the user interface of the Nintex K2 Five-powered permit application and renewal workflows, giving the entire platform a modern, consistent look and a significantly improved user experience. My performance-first approach ensured fast load times, mobile responsiveness, SEO optimization, and ease of maintenance for internal teams.","The result is a seamless and informative experience that promotes public accessibility, process transparency, and investor confidence—positioning Lagos EPPPS as a future-forward platform for planning and development."}	{"The Lagos EPPPS project reflects how thoughtful design and smart technology can enhance public service delivery. By combining modern web development with workflow optimization, the platform now provides a seamless digital experience for both citizens and government stakeholders—supporting transparency, efficiency, and the state’s broader vision for sustainable urban development."}	\N	https://lagoseppps.com.ng/	autobiz	{https://res.cloudinary.com/tobycodes/image/upload/v1743928773/Portfolio%20V2/Screenshot_47_larh4a.png,https://res.cloudinary.com/tobycodes/image/upload/v1743928775/Portfolio%20V2/Screenshot_73_va3fbq.png,https://res.cloudinary.com/tobycodes/image/upload/v1743928774/Portfolio%20V2/Screenshot_71_t3b8dx.png,https://res.cloudinary.com/tobycodes/image/upload/v1743928774/Portfolio%20V2/Screenshot_72_rb28q9.png}
f9d54603-4162-44b0-87f5-3d8cdc3fff3a	2025-04-06 16:07:35.112264+00	Nintex K2 Theme Redesign	k2theme	Designed Modern theme for various Nintex Automation processes	2023	K2 Five, HTML, SCSS, Javascript, Jquery	UI/UX Design · Front-End Dev · Digital Transformation	{sorting-web-development}	https://res.cloudinary.com/tobycodes/image/upload/v1743954928/Portfolio%20V2/LASGNET_1_njkm09.png	{"I redesigned outdated custom K2 Five themes into clean, modern, and user-friendly interfaces. By translating Figma designs into fully functional layouts using CSS and JavaScript, I was able to significantly enhance the user experience across multiple Nintex Automation forms and workflows.This not only aligned the visual styling with modern UI/UX principles but also improved usability for both internal teams and end users.","In addition, I followed brand-specific design guidelines to ensure each interface remained consistent with the visual identity of its respective organization—delivering tailored UI solutions that aligned with corporate standards."}	{"The result was a cohesive and responsive interface that elevated the overall look and functionality of the K2 environment—making automation processes more intuitive, accessible, and visually engaging."}	\N	https://drive.google.com/file/d/1VvA0v9I0LjoO5N_JuQEzrMiISzvI2ttT/view?usp=drive_link	lagosnet	{https://res.cloudinary.com/tobycodes/image/upload/v1743928771/Portfolio%20V2/Screenshot_45_lbomqi.png,https://res.cloudinary.com/tobycodes/image/upload/v1743928768/Portfolio%20V2/Screenshot_31_zxtutl.png,https://res.cloudinary.com/tobycodes/image/upload/v1743928769/Portfolio%20V2/Screenshot_41_gk4hjb.png,https://res.cloudinary.com/tobycodes/image/upload/v1743928772/Portfolio%20V2/Screenshot_42_guc9yh.png,https://res.cloudinary.com/tobycodes/image/upload/v1743928770/Portfolio%20V2/Screenshot_44_deb8jx.png}
\.

System.Object[]